
task partner_engagement_tracking: :environment do
  petr = Questionnaire.find_by(title: "Partner Engagement Tracking Form")
  petr ||= Questionnaire.create!(title: "Partner Engagement Tracking Form")

  petr_q1 = petr.questions.find_or_create_by(identifier: "partner_name")
  petr_q1.update(number: 1, question_type: :long_answer, required: false, text: "Organization:")
  petr_q2 = petr.questions.find_or_create_by(identifier: "partner_contact")
  petr_q2.update(number: 2, question_type: :long_answer, required: false, text: "Contact Name:")
  petr_q3 = petr.questions.find_or_create_by(identifier: "partner_role")
  petr_q3.update(number: 3, question_type: :long_answer, required: false, text: "Role:")
  petr_q4 = petr.questions.find_or_create_by(identifier: "partner_email")
  petr_q4.update(number: 4, question_type: :long_answer, required: false, text: "Email:")
  petr_q5 = petr.questions.find_or_create_by(identifier: "partner_phone")
  petr_q5.update(number: 5, question_type: :long_answer, required: false, text: "Phone Number:")
  petr_q6 = petr.questions.find_or_create_by(identifier: "partner_county")
  petr_q6.update(number: 6, question_type: :long_answer, required: false, text: "County:")
  petr_q7 = petr.questions.find_or_create_by(identifier: "partner_type")
  petr_q7.update(number: 7, question_type: :long_answer, required: false, text: "Partner Type:")
  petr_q8 = petr.questions.find_or_create_by(identifier: "partner_engagement_stage")
  petr_q8.update(number: 8, question_type: :long_answer, required: false, text: "Engagement Stage:")
  petr_q9 = petr.questions.find_or_create_by(identifier: "partner_communication")
  petr_q9.update(number: 9, question_type: :long_answer, required: false, text: "Recent Communication:")
  petr_q10 = petr.questions.find_or_create_by(identifier: "partner_communication_method")
  petr_q10.update(number: 10, question_type: :multiple_choice, required: false, text: "Method of Communication:")
  petr_q10.answers.find_or_create_by(text: "Email").update(number: 1, text: "Email")
  petr_q10.answers.find_or_create_by(text: "Phone").update(number: 2, text: "Phone")
  petr_q10.answers.find_or_create_by(text: "In Person").update(number: 3, text: "In-Person")
  petr_q11 = petr.questions.find_or_create_by(identifier: "partner_last_outreach_date")
  petr_q11.update(number: 11, question_type: :date_answer, required: false, text: "Last Outreach Date:")
  petr_q12 = petr.questions.find_or_create_by(identifier: "partner_communication_staff")
  petr_q12.update(number: 12, question_type: :long_answer, required: false, text: "ENC-HEAL Staff Provided Communication:")
  petr_q13 = petr.questions.find_or_create_by(identifier: "partner_next_step")
  petr_q13.update(number: 13, question_type: :long_answer, required: false, text: "Next Action Step:")
  petr_q14 = petr.questions.find_or_create_by(identifier: "partner_followup_notes")
  petr_q14.update(number: 14, question_type: :long_answer, required: false, text: "Follow-up Notes:")
  petr_q15 = petr.questions.find_or_create_by(identifier: "partner_challenges")
  petr_q15.update(number: 15, question_type: :long_answer, required: false, text: "Current or potential challenges:")
  petr_q16 = petr.questions.find_or_create_by(identifier: "partner_outcomes")
  petr_q16.update(number: 16, question_type: :long_answer, required: false, text: "Outcomes:")
end
