desc "Create or update the ENC-HEAL Training Tracking Form"
task training_tracking: :environment do
  ttf = Questionnaire.find_by(title: "Training Tracking Form")
  ttf ||= Questionnaire.create!(title: "Training Tracking Form")

  ttf_q1 = ttf.questions.find_or_create_by(identifier: "training_title")
  ttf_q1.update(number: 1, question_type: :long_answer, required: false, text: "Training Title:")
  ttf_q2 = ttf.questions.find_or_create_by(identifier: "training_topic")
  ttf_q2.update(number: 2, question_type: :long_answer, required: false, text: "Topic:")
  ttf_q3 = ttf.questions.find_or_create_by(identifier: "training_date")
  ttf_q3.update(number: 3, question_type: :date_answer, required: false, text: "Date:")
  ttf_q4 = ttf.questions.find_or_create_by(identifier: "training_provider")
  ttf_q4.update(number: 4, question_type: :long_answer, required: false, text: "Training Provided By:")
  ttf_q5 = ttf.questions.find_or_create_by(identifier: "training_total_hours")
  ttf_q5.update(number: 5, question_type: :number_answer, required: false, text: "Total Hours:")
  ttf_q6 = ttf.questions.find_or_create_by(identifier: "training_location")
  ttf_q6.update(number: 6, question_type: :long_answer, required: false, text: "Location:")
  ttf_q7 = ttf.questions.find_or_create_by(identifier: "training_type")
  ttf_q7.update(number: 7, question_type: :multiple_choice, required: false, text: "Type of Training Provided: (select all that apply)")
  ttf_q7.answers.find_or_create_by(text: "Staff Development").update(number: 1, text: "Staff Development")
  ttf_q7.answers.find_or_create_by(text: "CAC Training").update(number: 2, text: "CAC Training")
  ttf_q7.answers.find_or_create_by(text: "Community Training").update(number: 3, text: "Community Training")
  ttf_q7.answers.find_or_create_by(text: "SHEAL Team Training").update(number: 4, text: "SHEAL Team Training")
  ttf_q8 = ttf.questions.find_or_create_by(identifier: "training_staff_attended_count")
  ttf_q8.update(number: 8, question_type: :number_answer, required: false, text: "Number of ENC-HEAL Staff attended:")
  ttf_q9 = ttf.questions.find_or_create_by(identifier: "training_staff_attended_names")
  ttf_q9.update(number: 9, question_type: :long_answer, required: false, text: "Name of ENC-HEAL Staff in attendance:")
  ttf_q10 = ttf.questions.find_or_create_by(identifier: "training_partners_attended_names")
  ttf_q10.update(number: 10, question_type: :long_answer, required: false, text: "Name of ENC-HEAL Partners in attendance:")
  ttf_q11 = ttf.questions.find_or_create_by(identifier: "training_partners_attended_count")
  ttf_q11.update(number: 11, question_type: :number_answer, required: false, text: "If training provided by ENC-HEAL, please provide the number of ENC-HEAL Partners in attendance:")
  ttf_q12 = ttf.questions.find_or_create_by(identifier: "training_community_members_attended_count")
  ttf_q12.update(number: 12, question_type: :number_answer, required: false, text: "If training provided by ENC-HEAL, please provide the number of Community Members (such as faith leaders, business leaders, and any other members of the community) in attendance:")
  ttf_q13 = ttf.questions.find_or_create_by(identifier: "training_youth_serving_professionals_attended_count")
  ttf_q13.update(number: 13, question_type: :number_answer, required: false, text: "If training provided by ENC-HEAL, please provide the number of Youth Serving Professionals (teachers, educators, social workers, clinical providers, other healthcare workers, juvenile justice officers, etc) in attendance:")
  ttf_q14 = ttf.questions.find_or_create_by(identifier: "training_parents_attended_count")
  ttf_q14.update(number: 14, question_type: :number_answer, required: false, text: "If training provided by ENC-HEAL, please provide the number of Parents in attendance:")
  ttf_q15 = ttf.questions.find_or_create_by(identifier: "training_youth_attended_count")
  ttf_q15.update(number: 15, question_type: :number_answer, required: false, text: "If training provided by ENC-HEAL, please provide the number of Youth in attendance:")
  ttf_q16 = ttf.questions.find_or_create_by(identifier: "training_other_attended_count")
  ttf_q16.update(number: 16, question_type: :number_answer, required: false, text: "If training provided by ENC-HEAL, please provide the number of Other attendees in attendance:")
  ttf_q17 = ttf.questions.find_or_create_by(identifier: "training_post_assessment_completed")
  ttf_q17.update(number: 17, question_type: :single_choice, required: false, text: "Post Assessment Completed/Certificate Received:")
  ttf_q17.answers.find_or_create_by(text: "Yes").update(number: 1, text: "Yes")
  ttf_q17.answers.find_or_create_by(text: "No").update(number: 2, text: "No")
  ttf_q18 = ttf.questions.find_or_create_by(identifier: "training_notes")
  ttf_q18.update(number: 18, question_type: :long_answer, required: false, text: "Notes:")
  ttf_q19 = ttf.questions.find_or_create_by(identifier: "training_other_information")
  ttf_q19.update(number: 19, question_type: :long_answer, required: false, text: "Other Important Information:")
end
